### ISSUE TITLE
Update oauth2-client dependencies from 0.7.x to 0.10.x

### ISSUE THREAD

**Issue by BrainBust** [tpavlek/oauth2-twitch#1]
installing oauth2-twitch in tandem with oauth2-client using composer gives the following error: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for depotwarehouse/oauth2-twitch dev-master -> satisfiable by depotwarehouse/oauth2-twitch[dev-master].
    - depotwarehouse/oauth2-twitch dev-master requires league/oauth2-client 0.7.* -> no matching package found.
```

**Comment by tpavlek** [comment]
This is an easy fix, I'm just testing it with my stuff to ensure that nothing breaks in the upgrade (ramsey follows semVer nicely, so I don't suspect any breaks exist)

**Comment by BrainBust** [comment]
i could fork and update myself privately or wait for a push to packagist, either way no rush

**Comment by tpavlek** [comment]
I just tagged a new release, let me know if there are any problems with it.

I hope you weren't using Laravel 4 with this. If you were, I just fucked up.

**Comment by BrainBust** [comment]
1.1.0 worked like a charm, thank you!
