### ISSUE TITLE
Upgrading to oauth2-client 0.11.0?

### ISSUE THREAD

**Issue by mikeemoo** [tpavlek/oauth2-twitch#3]
Hi,

Do you have plans to upgrade to oauth2-client 0.11.0? If so, do you have an approximate ETA?

Many thanks.

**Comment by tpavlek** [comment]
Thanks for reminding me about this.

Gardening today, but I should have time to tag a release tomorrow.

If you need it faster and want to submit a pull for it I'll merge.

**Comment by mikeemoo** [comment]
Brilliant. Appreciated.

**Comment by tpavlek** [comment]
@mikeemoo 1.2.0 was just tagged - sorry I was a day late!

**Comment by mikeemoo** [comment]
Super! Thank you.
