### ISSUE TITLE
Not compatible with 2.0 version of league/oauth2-client

### ISSUE THREAD

**Issue by MadMikeyB** [tpavlek/oauth2-twitch#8]
Because in composer.json you list the following:

`"league/oauth2-client": "^1.3",`

Upon upgrading to league/oauth2-client 2.0, I can no longer use this version. Composer spits out an error.

Could you confirm whether this is compatible with league/oauth2-client 2.0 ? All the official league/ providers now require 2.0, so I cannot downgrade. 

Thanks!

**Comment by tpavlek** [comment]
I haven't upgraded this. I'd happily accept a pull - otherwise it'll have
to compete with my busy schedule

**Comment by MadMikeyB** [comment]
Thanks for the reply - I will look into submitting a PR.

**Comment by 0plus1** [comment]
HI @MadMikeyB,

I just pushed a commit to address this issue, please change your require in composer.json to pull from master and you will be sorted, if you can please report back if it works without issues I will create an official release.

Thanks

**Comment by tristanbes** [comment]
Hello, @0plus1 // @tpavlek 

Is that possible to tag a new release of your bundle (compliant with `league/oauth2-client 2.0`)  ? I don't like to put `dev-master` on my `composer.json`

I've been using your patch without any problem so far.

Thanks.

**Comment by tpavlek** [comment]
@tristanbes a new release was just tagged.

**Comment by tristanbes** [comment]
Thanks.
